### ISSUE TITLE
Add fuel pod and bench pod textures

### ISSUE THREAD

**Issue by Takelmeifter** [jonpas/JNS_Skycranes#12]
Currently no known way of accessing these textures - even in .paa form

crying inside.

**Comment by jonpas** [comment]
Currently no templates available, putting On Hold until someone creates one or BIS actually releases one.

**Comment by jonpas** [comment]
Added on Arma 3 Tools development branch today!
http://forums.bistudio.com/showthread.php?179347-Tools-Development-Branch-Changelog&p=2898811&viewfull=1#post2898811
